const USER_ROLES = {
    SUPPLIER: 'SUPPLIER',
    BUYER: 'BUYER',
    FARMER: 'FARMER',
    TRANSPORTER: 'TRANSPORTER',
    ADMIN: 'ADMIN',
};

const USER_STATUS = {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    PENDING: 'PENDING',
};

const LOCATION_TYPES = {
    HOME: 'HOME',
    BUSINESS: 'BUSINESS',
};

const PERMISSION_TYPES = {
    GRANT: 'GRANT',
    DENY: 'DENY',
};

const PRODUCT_STATUS = {
    ACTIVE: 'ACTIVE',
    SOLD: 'SOLD',
    EXPIRED: 'EXPIRED',
    INACTIVE: 'INACTIVE',
};

const LEAD_INTERACTION_TYPES = {
    VIEW: 'VIEW',
    CALL: 'CALL',
    WHATSAPP: 'WHATSAPP',
    MESSAGE: 'MESSAGE',
};

const SUBSCRIPTION_STATUS = {
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED',
};

const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
};

const PAYMENT_MODES = {
    UPI: 'UPI',
    CARD: 'CARD',
    NET_BANKING: 'NET_BANKING',
    WALLET: 'WALLET',
    CASH: 'CASH',
};

const NOTIFICATION_TYPES = {
    PRODUCT_ALERT: 'PRODUCT_ALERT',
    LEAD_SYSTEM: 'LEAD_SYSTEM',
    PAYMENT: 'PAYMENT',
    GENERAL: 'GENERAL',
};

const TRANSPORT_STATUS = {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
};

const VERIFICATION_STATUS = {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED',
};

const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
};

const JWT = {
    EXPIRES_IN: '7d',
    REFRESH_EXPIRES_IN: '30d',
};

const CACHE_TTL = {
    SHORT: 300,    // 5 minutes
    MEDIUM: 1800,  // 30 minutes
    LONG: 86400,   // 24 hours
};

module.exports = {
    USER_ROLES,
    USER_STATUS,
    LOCATION_TYPES,
    PERMISSION_TYPES,
    PRODUCT_STATUS,
    LEAD_INTERACTION_TYPES,
    SUBSCRIPTION_STATUS,
    PAYMENT_STATUS,
    PAYMENT_MODES,
    NOTIFICATION_TYPES,
    TRANSPORT_STATUS,
    VERIFICATION_STATUS,
    PAGINATION,
    JWT,
    CACHE_TTL,
};
